#pragma once
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
namespace cloudy {
constexpr int hilbertLength=511;
constexpr int hilbertLatency=(hilbertLength-1)/2;
constexpr int analyticChannels=12;
inline const std::array<float,hilbertLength>&hilbertTaps()noexcept{static const auto taps=[] {std::array<float,hilbertLength>h{};constexpr double pi=3.14159265358979323846;for(int n=0;n<hilbertLength;++n){const int m=n-hilbertLatency;if(m!=0&&(std::abs(m)&1)!=0){const double ideal=2.0/(pi*double(m));const double window=.42-.5*std::cos(2*pi*n/double(hilbertLength-1))+.08*std::cos(4*pi*n/double(hilbertLength-1));h[size_t(n)]=float(ideal*window);}}return h;}();return taps;}
struct AnalyticPair{std::array<float,hilbertLength>history{};int write=0;void reset()noexcept{history.fill(0);write=0;}std::array<float,2>process(float x)noexcept{history[size_t(write)]=std::isfinite(x)?x:0;const int delayedIndex=(write-hilbertLatency+hilbertLength)%hilbertLength;const float real=history[size_t(delayedIndex)];double quadrature=0;const auto&taps=hilbertTaps();for(int k=0;k<hilbertLength;++k){int index=write-k;if(index<0)index+=hilbertLength;quadrature+=double(taps[size_t(k)])*double(history[size_t(index)]);}if(++write==hilbertLength)write=0;return{real,float(quadrature)};}};
struct OnePoleSplit{float state=0,coefficient=0;void prepare(double sr,double frequency=1200)noexcept{coefficient=float(1-std::exp(-2*3.14159265358979323846*frequency/std::max(1.,sr)));state=0;}void reset()noexcept{state=0;}void process(float x,float&low,float&high)noexcept{state+=coefficient*(x-state);low=state;high=x-state;}};
class AnalysisBank{std::array<OnePoleSplit,2>split{};std::array<std::array<AnalyticPair,3>,2>pair{};public:void prepare(double sr)noexcept{for(int c=0;c<2;++c){split[size_t(c)].prepare(sr);for(auto&p:pair[size_t(c)])p.reset();}}void reset()noexcept{for(int c=0;c<2;++c){split[size_t(c)].reset();for(auto&p:pair[size_t(c)])p.reset();}}std::array<float,analyticChannels>process(std::array<float,2>input)noexcept{std::array<float,analyticChannels>out{};for(int c=0;c<2;++c){const float x=std::isfinite(input[size_t(c)])?input[size_t(c)]:0;float low=0,high=0;split[size_t(c)].process(x,low,high);auto full=pair[size_t(c)][0].process(x),lo=pair[size_t(c)][1].process(low),hi=pair[size_t(c)][2].process(high);int b=c*6;out[size_t(b)]=full[0];out[size_t(b+1)]=full[1];out[size_t(b+2)]=lo[0];out[size_t(b+3)]=lo[1];out[size_t(b+4)]=hi[0];out[size_t(b+5)]=hi[1];}return out;}};
inline float complexHarmonic(float real,float imaginary,int order)noexcept{const float amplitude=std::hypot(real,imaginary);if(!std::isfinite(amplitude)||amplitude<1e-7f)return 0;const float ur=real/amplitude,ui=imaginary/amplitude;float zr=1,zi=0;for(int n=0;n<std::clamp(order,2,11);++n){const float nr=zr*ur-zi*ui;zi=zr*ui+zi*ur;zr=nr;}return std::isfinite(zr)?amplitude*zr:0;}
inline float blendColor(float full,float low,float high,float color)noexcept{color=std::clamp(color,-1.f,1.f);const float bias=std::abs(color);const float selected=color<0?low:high;return full+bias*(selected*1.35f-full);}
class DryDelay{static constexpr int capacity=4096;std::array<std::array<float,capacity>,2>history{};int write=0,delay=0;public:void prepare(int samples)noexcept{delay=std::clamp(samples,0,capacity-1);reset();}void reset()noexcept{for(auto&h:history)h.fill(0);write=0;}std::array<float,2>process(std::array<float,2>x)noexcept{for(int c=0;c<2;++c)history[size_t(c)][size_t(write)]=x[size_t(c)];int read=write-delay;if(read<0)read+=capacity;std::array<float,2>y{history[0][size_t(read)],history[1][size_t(read)]};if(++write==capacity)write=0;return y;}};
}
