#pragma once
#include <array>
#include <algorithm>
#include <cmath>
namespace cloudy {
inline float chebyshev(float x, int order) noexcept { x=std::clamp(x,-1.0f,1.0f); if(order<=0)return 1.0f;if(order==1)return x;float t0=1.0f,t1=x;for(int n=2;n<=order;++n){const float t=2.0f*x*t1-t0;t0=t1;t1=t;}return t1; }
struct OnePoleSplit { float state=0.0f,coefficient=0.0f; void prepare(double sr,double frequency=1200.0) noexcept {coefficient=float(1.0-std::exp(-2.0*3.14159265358979323846*frequency/std::max(1.0,sr)));state=0.0f;} void process(float x,float& low,float& high) noexcept {state+=coefficient*(x-state);low=state;high=x-state;} };
struct Envelope { float value=0.0f,attack=0.0f,release=0.0f; void prepare(double sr) noexcept {value=0.0f;attack=float(std::exp(-1.0/(std::max(1.0,sr)*0.002)));release=float(std::exp(-1.0/(std::max(1.0,sr)*0.080)));} float process(float x) noexcept {const float level=std::abs(x);const float c=level>value?attack:release;value=level+c*(value-level);return value;} };
struct DCBlock {float x1=0.0f,y1=0.0f;float process(float x) noexcept {const float y=x-x1+0.995f*y1;x1=x;y1=y;return y;}void reset() noexcept{x1=y1=0.0f;}};
class Engine {std::array<OnePoleSplit,2> split{};std::array<std::array<Envelope,2>,2> envelope{};std::array<DCBlock,2> dc{};float amount=0,targetAmount=0,color=0,targetColor=0,output=1,targetOutput=1,smoothing=0;int harmonic=9;float generated(float x,Envelope& follower,int order) noexcept {const float env=follower.process(x);if(env<1.0e-6f)return 0.0f;const float normalized=std::clamp(x/(env+1.0e-5f),-1.0f,1.0f);return chebyshev(normalized,order)*env;}
public:void prepare(double sr) noexcept {for(int c=0;c<2;++c){split[size_t(c)].prepare(sr);envelope[size_t(c)][0].prepare(sr);envelope[size_t(c)][1].prepare(sr);dc[size_t(c)].reset();}smoothing=float(std::exp(-1.0/(std::max(1.0,sr)*0.015)));amount=targetAmount;color=targetColor;output=targetOutput;}void configure(float amountPercent,float colorPercent,float outputDb,int order) noexcept {targetAmount=std::clamp(amountPercent*.01f,0.0f,1.0f);targetColor=std::clamp(colorPercent*.01f,-1.0f,1.0f);const float db=std::clamp(outputDb,-100.0f,6.0f);targetOutput=db<=-99.995f?0.0f:std::pow(10.0f,db/20.0f);harmonic=std::clamp(order,2,11);}std::array<float,2> process(std::array<float,2> input,bool bypassed=false) noexcept {amount=targetAmount+smoothing*(amount-targetAmount);color=targetColor+smoothing*(color-targetColor);output=targetOutput+smoothing*(output-targetOutput);if(bypassed)return input;const float wet=.34f*amount*amount;const float lowWeight=color>=0?1.0f-.92f*color:1.0f+.80f*-color;const float highWeight=color<=0?1.0f-.92f*-color:1.0f+.80f*color;std::array<float,2> result{};for(int c=0;c<2;++c){const float x=std::isfinite(input[size_t(c)])?input[size_t(c)]:0.0f;float low=0,high=0;split[size_t(c)].process(x,low,high);const float h=lowWeight*generated(low,envelope[size_t(c)][0],harmonic)+highWeight*generated(high,envelope[size_t(c)][1],harmonic);result[size_t(c)]=(x+wet*dc[size_t(c)].process(h))*output;}return result;}};
}
